In [20]:
import numpy as np


In [21]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x


In [22]:
abc = np.array([[1,-2,3],
       [7,-5,-3]])

In [23]:
naive_relu(abc)


array([[1, 0, 3],
       [7, 0, 0]])

In [24]:
abc


array([[ 1, -2,  3],
       [ 7, -5, -3]])

In [25]:
def naive_add(x,y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] = x[i,j] + y[i,j]
    return x

In [26]:
xyz = np.array([[1, 0, 3],
       [7, 0, 0]])

In [27]:
naive_add(abc,xyz)

array([[ 2, -2,  6],
       [14, -5, -3]])

In [28]:
z=abc+xyz

In [29]:
z

array([[ 2, -2,  6],
       [14, -5, -3]])

In [30]:
np.maximum(z,0)

array([[ 2,  0,  6],
       [14,  0,  0]])

In [31]:
def naive_add_matrix_and_vector(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape
    x = x.copy()
    for i in range (x.shape[0]):
        for j in range (x.shape[1]):
            x[i,j] += y[j]
    return x

In [34]:
x = np.random.random((3,5,2))
y = np.random.random((5,2))
z = np.maximum(x,y)

In [37]:
print(x);print('\n');print(y)

[[[0.03449183 0.04601248]
  [0.46596151 0.23986001]
  [0.63005935 0.26982743]
  [0.8085008  0.91428184]
  [0.89763085 0.88901164]]

 [[0.48845383 0.32530607]
  [0.83858766 0.51252614]
  [0.20753858 0.873458  ]
  [0.58782371 0.1441483 ]
  [0.17552913 0.04171435]]

 [[0.42317697 0.02673822]
  [0.13420199 0.91295413]
  [0.41933199 0.34968167]
  [0.20032591 0.2718516 ]
  [0.13183728 0.07700311]]]


[[0.97363433 0.1812213 ]
 [0.19905305 0.36533783]
 [0.89685766 0.10232744]
 [0.22998804 0.49961733]
 [0.64185164 0.29478231]]


In [47]:
def naive_matrix_vector_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i,j] * y[j]
    return z

In [58]:
x = np.array([[1,2,3],
             [4,5,6]])
y = np.array([-1,1,-1])

In [59]:
z = naive_matrix_vector_dot(x,y)

In [60]:
print(z)

[-2. -5.]


In [64]:
print(x.shape,y.shape)

(2, 3) (3,)


In [66]:
x.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [69]:
x.reshape(3,1,2)

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [71]:
y.reshape(1,1,3,1,1,1,1)

array([[[[[[[-1]]]],



         [[[[ 1]]]],



         [[[[-1]]]]]]])